---
apiVersion: v1
kind: Namespace
metadata:
  name: api
---
apiVersion: v1
kind: Namespace
metadata:
  name: frontend
---
apiVersion: v1
kind: Namespace
metadata:
  name: backend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: api
  name: api
  namespace: api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  strategy: {}
  template:
    metadata:
      labels:
        app: api
    spec:
      containers:
      - image: nginx
        name: nginx
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - image: redis
        name: redis
---
apiVersion: ztnp.io/v1alpha1
kind: SymmetricRule
metadata:
  name: frontend-to-api
spec:
  from:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: frontend
    podSelector:
      matchLabels:
        app: frontend
  to:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: api
    podSelector:
      matchLabels:
        app: api
  ports:
  - port: 80
    protocol: TCP
  enforce: true
  prune: true
---
apiVersion: ztnp.io/v1alpha1
kind: SymmetricRule
metadata:
  name: api-to-backend
spec:
  from:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: api
    podSelector:
      matchLabels:
        app: api
  to:
    namespaceSelector:
      matchLabels:
        kubernetes.io/metadata.name: backend
    podSelector:
      matchLabels:
        app: backend
  ports:
  - port: 6379
    protocol: TCP
  enforce: true
  prune: true
